# Basic options
title: R - Beginners to Intermediates
short_name: R intro
developers: [Rebecca Smith, Fiona Warren, Theresa Wacker, Laura Roldan Gomez]
description: Over four sessions this workshop will provide an all-purpose introduction to the R programming language and may provide an accessible entry to computer programming in general.
n_sessions: 4
prereq: NA
url: https://uniexeterrse.github.io/intro-to-r

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
